# Generated by Django 5.0.7 on 2025-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default='Ground Floor', help_text='Floor location of the room', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference Room'), ('meeting', 'Meeting Room'), ('boardroom', 'Boardroom'), ('training', 'Training Room'), ('event_hall', 'Event Hall'), ('auditorium', 'Auditorium'), ('other', 'Other')], help_text='Type/category of the room', max_length=50),
        ),
    ]
