# Generated by Django 5.0.7 on 2025-09-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_floor_alter_room_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
    ]
