# Generated by Django 5.0.7 on 2025-09-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_attendee_count_booking_expected_attendees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcurementOrder',
        ),
    ]
