# Generated by Django 4.2.11 on 2025-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_delete_procurementorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_dates',
            field=models.JSONField(blank=True, default=list, help_text='Array of selected dates for multi-day bookings (e.g., ["2025-10-06", "2025-10-08", "2025-10-10"])'),
        ),
    ]
